# motion def:
motion_file: recorder_gnss_ins_sim_speedconstant.csv
# IMU params:
imu: 1
# sample frequency of simulated GNSS/IMU data:
sample_frequency:
    imu: 100.0
    gps: 10.0
# topic name:
topic_name_imu: /sim/sensor/imu
topic_name_gt: /sim/gt
# output rosbag path:
output_path: /workspace/assignments/06-imu-navigation/src/gnss_ins_sim/allan_variance_analysis
# output name:
output_name: speedconstant.bag